<Project>
  <PropertyGroup>
    <Version>1.1.2</Version>
    <BundledIl2CppInteropRevision>2a16370dd441c496ca5c99cd61a7af9e87caa5d3</BundledIl2CppInteropRevision>
    <BundledIl2CppInteropRepositoryUrl>https://github.com/LemonLoaderX/Il2CppInterop.git</BundledIl2CppInteropRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="BundledIl2CppInteropRevision"
                      Value="$(BundledIl2CppInteropRevision)" />
  </ItemGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'LemonLoader.Patcher.Core'">
    <Using Include="LemonLoader.Patcher.Core" />
  </ItemGroup>
</Project>
