<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <None Include="../../.config/dotnet-tools.json" Link=".config/dotnet-tools.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
