<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/LemonLoader.Patcher.Core/LemonLoader.Patcher.Core.csproj" />
    <ProjectReference Include="../../src/LemonLoader.Patcher.CLI/LemonLoader.Patcher.CLI.csproj" />
  </ItemGroup>
</Project>
