<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LemonLoader.Patcher.Core/LemonLoader.Patcher.Core.csproj" />
    <None Include="../../.config/dotnet-tools.json" Link=".config/dotnet-tools.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
